- name: 05_pgsql-patroni
  hosts:
    - database
#    - hl-pg01
#    - hl-pg02
#    - hl-pg03
  become: true

  roles:
    - 05_pgsql_consul-client
    - 05_pgsql-patroni-server
    - 05_pgsql_optimization