---
####### ВНИМАНИЕ!!! Удаление БД и пользователя zabbix #######
################# Если не нужно, отключить! #################
- name: drop zabbix database
  postgresql_db:
    login_host: "{{ HOST_NAME_PG_CON_POOL_VIP }}.{{ FAKE_DOMAIN }}"
    login_user: postgres
    login_password: "{{ PASS_POSTGRES_FOR_DB }}"
    port: "{{ PORT_FOR_DB_CLIENT }}"
    name: zabbix
    state: absent

- name: remove zabbix user
  postgresql_user:
    login_host: "{{ HOST_NAME_PG_CON_POOL_VIP }}.{{ FAKE_DOMAIN }}"
    login_user: postgres
    login_password: "{{ PASS_POSTGRES_FOR_DB }}"
    port: "{{ PORT_FOR_DB_CLIENT }}"
    name: zabbix
    state: absent
#############################################################

- name: create zabbix user
  postgresql_user:
    login_host: "{{ HOST_NAME_PG_CON_POOL_VIP }}.{{ FAKE_DOMAIN }}"
    login_user: postgres
    login_password: "{{ PASS_POSTGRES_FOR_DB }}"
    port: "{{ PORT_FOR_DB_CLIENT }}"
    #db: template1
    name: zabbix
    password: "{{ PASS_ZAB_FOR_DB }}"
    encrypted: true
    state: present

- name: create zabbix database
  postgresql_db:
    login_host: "{{ HOST_NAME_PG_CON_POOL_VIP }}.{{ FAKE_DOMAIN }}"
    login_user: postgres
    login_password: "{{ PASS_POSTGRES_FOR_DB }}"
    port: "{{ PORT_FOR_DB_CLIENT }}"
    name: zabbix
    owner: zabbix
    #encoding: UTF-8
    template: template1
    state: present

########## Почему-то база заливается повреждённой ##########
#- name: restore zabbix database from create.sql.gz
#  postgresql_db:
#    login_host: "{{ HOST_NAME_PG_CON_POOL_VIP }}.{{ FAKE_DOMAIN }}"
#    login_user: postgres
#    login_password: "{{ PASS_POSTGRES_FOR_DB }}"
#    port: "{{ PORT_FOR_DB_CLIENT }}"
#    name: zabbix
#    owner: zabbix
#    state: restore
#    #target: "{{ zabbix_sql_gz }}"
#    target: /usr/share/doc/zabbix-server-pgsql-4.2.7/create.sql.gz

- name: restore zabbix database from create.sql.gz
  shell:
    zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | psql -U zabbix -h {{ HOST_NAME_PG_CON_POOL_VIP }} -p {{ PORT_FOR_DB_CLIENT }} zabbix

########## При работе через odyssey пользователь postgres
########## не имеет доступа к схеме public чужой БД.
########## Поэтому здесь обращаемся на VIP-адрес кластера patroni,
########## а не на VIP-адрес odyssey.
########## Написал разработчикам issue.
#- name: setting a password for the Admin user (real username "Zabbix") to access the web interface
#  postgresql_query:
#    login_host: "{{ HOST_NAME_PG_CON_POOL_VIP }}.{{ FAKE_DOMAIN }}"
#    login_user: postgres
#    login_password: "{{ PASS_POSTGRES_FOR_DB }}"
#    port: "{{ PORT_FOR_DB_CLIENT }}"
#    db: zabbix
#    query: update users set passwd=md5('{{ PASS_FOR_WEB_GUI_ZABBIX }}') where alias='Admin'

- name: setting a password for the Admin user (real username "Zabbix") to access the web interface
  postgresql_query:
    login_host: "{{ HOST_NAME_PG_CON_POOL_VIP }}.{{ FAKE_DOMAIN }}"
    login_user: zabbix
    login_password: "{{ PASS_ZAB_FOR_DB }}"
    port: "{{ PORT_FOR_DB_CLIENT }}"
    db: zabbix
    query: update users set passwd=md5('{{ PASS_FOR_WEB_GUI_ZABBIX }}') where alias='Admin'
