---
- name: install device-mapper-persistent-data, lvm2
  yum:
    name: device-mapper-persistent-data, lvm2
    state: latest

- name: import docker repo a key from a url
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: add repo docker-ce
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker-ce, docker-ce-cli, containerd.io
  yum:
    name: docker-ce, docker-ce-cli, containerd.io
    state: latest
  notify:
    - docker restart

- name: copy yandextank directory
  copy:
    src: yandextank
    dest: /root/
    owner: root
    group: root

- name: put load.yaml template
  template:
    src: load.yaml.j2
    dest: /root/yandextank/load.yaml
    owner: root
    group: root
    mode: '0644'
