---
- name: install packages for php
  yum:
    name:
    - php-pecl-apcu
    - php-pecl-zendopcache
    - memcached
    - memcached-devel
    - php-pecl-memcache
    - redis
    - php-pecl-redis
    state: latest
  notify:
    - memcached restart
    - redis restart

- name: editinig php-fpm.d-www.conf
  shell: |
    sed -i 's/pm = dynamic/pm = static/g' /etc/php-fpm.d/www.conf
    sed -i 's/pm.max_children = 50/pm.max_children = 150/g' /etc/php-fpm.d/www.conf
    sed -i 's/;rlimit_files = 1024/rlimit_files = 16384/g' /etc/php-fpm.d/www.conf
    sed -i 's/;pm.max_requests = 500/pm.max_requests = 500/g' /etc/php-fpm.d/www.conf

- name: create directory for php-fpm.service override.conf
  file:
    path: /etc/systemd/system/php-fpm.service.d
    state: directory
    mode: '0755'

- name: copy override.conf (increase in the number of opened files php-fpm to 16384)
  copy:
    src: override_php-fpm.conf
    dest: /etc/systemd/system/php-fpm.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - php-fpm restart

- name: editinig /etc/nginx/nginx.conf
  shell: sed -i 's/worker_connections 1024;/worker_connections 16384;/g' /etc/nginx/nginx.conf

- name: create directory for nginx.service override.conf
  file:
    path: /etc/systemd/system/nginx.service.d
    state: directory
    mode: '0755'

- name: copy override.conf (increase in the number of opened files nginx to 16384)
  copy:
    src: override_nginx.conf
    dest: /etc/systemd/system/nginx.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - nginx restart

- name: edit sysctl.conf
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { key: "net.core.rmem_max", value: "16777216" }
    - { key: "net.ipv4.tcp_rmem", value: "4096 87380 16777216" }
    - { key: "net.core.wmem_max", value: "16777216" }
    - { key: "net.ipv4.tcp_wmem", value: "4096 16384 16777216" }
    - { key: "net.ipv4.tcp_fin_timeout", value: "20" }
    - { key: "net.ipv4.tcp_tw_reuse", value: "1" }
    - { key: "net.core.netdev_max_backlog", value: "10000" }
    - { key: "net.ipv4.ip_local_port_range", value: "15000 65001" }
