---
- name: install haproxy
  yum:
    name: haproxy
    state: latest

- name: put haproxy.cfg template
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify:
    - haproxy restart
