---
- name: keepalived restart
  systemd:
    daemon_reload: yes
    name: keepalived
    state: restarted
    enabled: yes

- name: haproxy restart
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
