---
- name: installation of packages for assembling rpm vp-manager
  yum:
    name:
      - git
      - golang
      - rpm-build
      - rpmdevtools
      - ruby-devel
      - gcc
      - make
      - rpm-build
      - rubygems
    state: latest

- name: install fpm with gem
  gem:
    name: fpm
    user_install: no
    state: latest

#gem install ffi --version 1.11.2
- name: install ffi version 1.11.2 with gem
  gem:
    name: ffi
    version: 1.11.2
    user_install: no
    state: present

- name: create a symbolic link for fpm
  file:
    src: /usr/local/bin/fpm
    dest: /usr/sbin/fpm
    owner: root
    group: root
    state: link

- name: create go directory in home root user
  file:
    path: /root/go
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: modify .bash_profile
  blockinfile:
    dest: /root/.bash_profile
    block: |
      export GOPATH=$HOME/go
#      export GOBIN=$GOPATH/bin
#      export PATH=$GOBIN:$PATH:/root/go/bin
    marker: "# {mark} ANSIBLE MANAGED BLOCK - changes for golang"
    insertafter: EOF
    create: yes

- name: download vip-manager
  shell: go get github.com/cybertec-postgresql/vip-manager
#  environment:
#    GOPATH: $HOME/go

- name: assembly of the rpm package vip-manager
  make:
    chdir: /root/go/src/github.com/cybertec-postgresql/vip-manager
    target: package-rpm
#  environment:
#    GOPATH: $HOME/go
#    PATH: $PATH:/usr/local/bin

- name: install vip-manager rpm
  yum:
    name: /root/go/src/github.com/cybertec-postgresql/vip-manager/vip-manager_0.6-1_amd64.rpm
    state: present

- name: put vip-manager.yml template
  template:
   src: vip-manager.yml.j2
   dest: /etc/default/vip-manager.yml
   owner: root
   group: root
   mode: '0644'
  notify:
    - vip-manager start and enable
