---
- name: memcached restart
  systemd:
    name: memcached
    state: restarted
    enabled: yes

- name: redis restart
  systemd:
    name: redis
    state: restarted
    enabled: yes

- name: php-fpm restart
  systemd:
    name: php-fpm
    daemon-reload: yes
    state: restarted
    enabled: yes

- name: nginx restart
  systemd:
    name: nginx
    daemon-reload: yes
    state: restarted
    enabled: yes
