---
- name: install pcs, pacemaker, corosync
  yum:
    name:
      - pcs
      - pacemaker
      - corosync
    state: latest

- name: change password for hacluster user
  shell:
    echo {{ PASS_HACLUSTER_USER }} | passwd --stdin hacluster

- name: start pcsd.service
  systemd:
    name: pcsd
    state: started
    enabled: yes

- name: create and change ownership of a IPaddr3 directory
  file:
    path: /usr/lib/ocf/resource.d/percona
    state: directory
    mode: '0755'
    owner: root
    group: root
    recurse: yes

- name: download IPaddr3
  get_url:
    url: https://raw.githubusercontent.com/percona/percona-pacemaker-agents/master/agents/IPaddr3
    dest: /usr/lib/ocf/resource.d/percona/IPaddr3
    owner: root
    group: root
    mode: '0755'
